"""Tests for ContextFile concept."""

import pytest
from pathlib import Path
import tempfile
import os
from uuid import UUID

# Override settings before importing modules
os.environ["DATABASE_PATH"] = str(Path(tempfile.gettempdir()) / "test_crabgrass_context.duckdb")
os.environ["STORAGE_ROOT"] = str(Path(tempfile.gettempdir()) / "test_crabgrass_storage")

from crabgrass.db.connection import get_connection, close_connection, reset_database
from crabgrass.db.migrations import run_migrations, SALLY_USER_ID, ACME_ORG_ID
from crabgrass.concepts.idea import IdeaConcept
from crabgrass.concepts.context_file import ContextFileConcept, context_file_concept
from crabgrass.sync.synchronizations import on_idea_created


@pytest.fixture(autouse=True)
def clean_db():
    """Reset database before each test."""
    reset_database()
    get_connection()
    run_migrations()
    yield
    close_connection()


@pytest.fixture
def idea_concept():
    """Create an IdeaConcept instance."""
    return IdeaConcept()


@pytest.fixture
def test_idea(idea_concept):
    """Create a test idea with kernel files initialized."""
    idea = idea_concept.create(ACME_ORG_ID, SALLY_USER_ID, "Test Idea")
    on_idea_created(idea)
    return idea


class TestContextFileConcept:
    """Tests for ContextFileConcept."""

    def test_create_context_file(self, test_idea):
        """Test creating a context file."""
        file = context_file_concept.create(
            idea_id=test_idea.id,
            filename="notes.md",
            content="# Notes\n\nSome research notes.",
            user_id=SALLY_USER_ID,
            created_by_agent=False,
        )

        assert file.filename == "notes.md"
        assert "# Notes" in file.content
        assert file.created_by_agent is False
        assert file.created_by == SALLY_USER_ID

    def test_create_agent_generated_file(self, test_idea):
        """Test creating an agent-generated context file."""
        file = context_file_concept.create(
            idea_id=test_idea.id,
            filename="feedback-tasks.md",
            content="# Idea Feedback & Tasks\n\nGenerated by CoherenceAgent.",
            user_id=None,
            created_by_agent=True,
        )

        assert file.filename == "feedback-tasks.md"
        assert file.created_by_agent is True
        assert file.created_by is None

    def test_get_context_file_by_name(self, test_idea):
        """Test getting a context file by filename."""
        context_file_concept.create(
            idea_id=test_idea.id,
            filename="research.md",
            content="Research content",
            user_id=SALLY_USER_ID,
        )

        file = context_file_concept.get(test_idea.id, "research.md")

        assert file is not None
        assert file.filename == "research.md"

    def test_get_nonexistent_file_returns_none(self, test_idea):
        """Test getting a non-existent file returns None."""
        file = context_file_concept.get(test_idea.id, "doesnotexist.md")
        assert file is None

    def test_update_context_file(self, test_idea):
        """Test updating a context file."""
        context_file_concept.create(
            idea_id=test_idea.id,
            filename="notes.md",
            content="Original content",
            user_id=SALLY_USER_ID,
        )

        updated = context_file_concept.update(
            idea_id=test_idea.id,
            filename="notes.md",
            content="Updated content with more detail.",
        )

        assert updated is not None
        assert "Updated content" in updated.content

    def test_create_or_update_creates_new(self, test_idea):
        """Test create_or_update creates a new file if it doesn't exist."""
        file = context_file_concept.create_or_update(
            idea_id=test_idea.id,
            filename="new-file.md",
            content="New file content",
            created_by_agent=True,
        )

        assert file.filename == "new-file.md"

    def test_create_or_update_updates_existing(self, test_idea):
        """Test create_or_update updates an existing file."""
        # Create the file first
        context_file_concept.create(
            idea_id=test_idea.id,
            filename="feedback-tasks.md",
            content="Version 1",
            created_by_agent=True,
        )

        # Update via create_or_update
        file = context_file_concept.create_or_update(
            idea_id=test_idea.id,
            filename="feedback-tasks.md",
            content="Version 2 - updated",
            created_by_agent=True,
        )

        assert "Version 2" in file.content

    def test_list_context_files(self, test_idea):
        """Test listing all context files for an idea."""
        context_file_concept.create(
            idea_id=test_idea.id,
            filename="file1.md",
            content="Content 1",
            user_id=SALLY_USER_ID,
        )
        context_file_concept.create(
            idea_id=test_idea.id,
            filename="file2.md",
            content="Content 2",
            user_id=SALLY_USER_ID,
        )

        files = context_file_concept.list(test_idea.id)

        assert len(files) == 2
        filenames = {f.filename for f in files}
        assert "file1.md" in filenames
        assert "file2.md" in filenames

    def test_list_empty_returns_empty_list(self, test_idea):
        """Test listing returns empty list when no files exist."""
        files = context_file_concept.list(test_idea.id)
        assert files == []

    def test_invalid_filename_rejected(self, test_idea):
        """Test that invalid filenames are rejected."""
        with pytest.raises(ValueError) as exc_info:
            context_file_concept.create(
                idea_id=test_idea.id,
                filename="invalid name.md",  # Has space
                content="Content",
                user_id=SALLY_USER_ID,
            )
        assert "Invalid filename" in str(exc_info.value)

    def test_filename_without_md_rejected(self, test_idea):
        """Test that filenames without .md extension are rejected."""
        with pytest.raises(ValueError) as exc_info:
            context_file_concept.create(
                idea_id=test_idea.id,
                filename="notes.txt",
                content="Content",
                user_id=SALLY_USER_ID,
            )
        assert "Invalid filename" in str(exc_info.value)

    def test_file_size_limit(self, test_idea):
        """Test that files exceeding size limit are rejected."""
        # Create content larger than 50KB
        large_content = "x" * (51 * 1024)

        with pytest.raises(ValueError) as exc_info:
            context_file_concept.create(
                idea_id=test_idea.id,
                filename="large-file.md",
                content=large_content,
                user_id=SALLY_USER_ID,
            )
        assert "Content too large" in str(exc_info.value)

    def test_size_bytes_calculated(self, test_idea):
        """Test that size_bytes is correctly calculated."""
        content = "Hello, World!"
        file = context_file_concept.create(
            idea_id=test_idea.id,
            filename="small.md",
            content=content,
            user_id=SALLY_USER_ID,
        )

        assert file.size_bytes == len(content.encode("utf-8"))
